# Generated by Django 2.2.12 on 2020-05-21 05:59

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200521_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='excerpt',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=70, null=True),
        ),
    ]
