# Generated by Django 2.2.12 on 2020-05-21 06:10

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postpage_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='excerpt',
            field=wagtail.core.fields.StreamField([('excerpt', wagtail.core.blocks.TextBlock())], blank=True, null=True),
        ),
    ]
