# Generated by Django 2.2.12 on 2020-05-21 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200521_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpage',
            name='excerpt',
        ),
    ]
