# Generated by Django 2.2.12 on 2020-05-21 06:31

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200521_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpage',
            name='body',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock()), ('codeblock', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.StreamBlock([('text', wagtail.core.blocks.RichTextBlock()), ('excerpt', wagtail.core.blocks.RichTextBlock())])), ('paragraph', wagtail.core.blocks.StreamBlock([('text', wagtail.core.blocks.RichTextBlock()), ('excerpt', wagtail.core.blocks.RichTextBlock())])), ('code', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('bash', 'Bash/Shell'), ('css', 'CSS'), ('diff', 'diff'), ('html', 'HTML'), ('javascript', 'Javascript'), ('json', 'JSON'), ('python', 'Python'), ('scss', 'SCSS'), ('yaml', 'YAML')], help_text='Coding language', identifier='language', label='Language')), ('code', wagtail.core.blocks.TextBlock(identifier='code', label='Code'))], label='Code'))])), ('excerpt', wagtail.core.blocks.RichTextBlock())], blank=True, null=True),
        ),
    ]
